package hannah.bd.getitwrite

object GlobalVariables {
    val writingPrompts = mutableListOf(
        "Write about a character who wakes up with no reflection.",
        "Describe a city where everyone forgets everything at midnight.",
        "Write a story from the perspective of a tree in a busy park.",
        "A letter arrives 10 years late — and changes everything.",
        "Your main character can hear lies — but only from animals.",
        "The sun doesn't rise one morning. No one knows why.",
        "Write a breakup letter between a writer and their muse.",
        "A librarian discovers a book that predicts the future.",
        "Describe the last 60 seconds before a secret is revealed.",
        "Your character can pause time, but only for 3 minutes per day.",
        "Write about a world where people trade dreams as currency.",
        "Your character’s shadow starts acting independently.",
        "An AI gains sentience and immediately wants to write poetry.",
        "A ghost is haunting your character — to help them finish their novel.",
        "Write a dialogue between two exes trapped in an elevator.",
        "A magician's last trick accidentally opens a portal.",
        "Describe a ritual performed once every hundred years.",
        "Your character wakes up in someone else’s memory.",
        "An artist discovers their paintings come true.",
        "Every decision today is being controlled by a coin flip.",
        "Write a scene where no one can lie — even by omission.",
        "A ship is lost at sea, but the ocean speaks to one passenger.",
        "Write a fairytale set in a cyberpunk dystopia.",
        "Describe a meal that saves someone’s life.",
        "Two strangers discover they share the same recurring dream.",
        "A haunted house demands a story in exchange for safe passage.",
        "Your protagonist finds a notebook labeled ‘DO NOT WRITE HERE.’",
        "A planet where the seasons change every day.",
        "Write about the invention of an emotion.",
        "A love story that starts with a mistaken identity at a funeral.",
        "Your character wakes up in a world run by children.",
        "Every mirror shows a different version of the person looking in.",
        "Write about someone who remembers every version of reality.",
        "A dragon’s hoard contains only books.",
        "A town where people age backward.",
        "A love letter accidentally mailed to the wrong person.",
        "Describe a character who’s allergic to the future.",
        "Write a scene using only dialogue.",
        "A detective solves crimes by dreaming about them.",
        "A wedding is interrupted by a character from a forgotten story.",
        "Your character inherits a lighthouse and a cryptic diary.",
        "Write about a forgotten god returning for one last favor.",
        "Your character finds a map tattooed on their skin.",
        "Describe the end of a world — and the beginning of another.",
        "A spell goes wrong and swaps two characters’ writing styles.",
        "Write a monologue from a villain just before they change sides.",
        "A time traveler gets stuck in their least favorite era.",
        "Two rival authors are forced to co-write a bestseller.",
        "A character is cursed to speak only in song lyrics.",
        "Describe an underground library known only to a few.",
        "Your character discovers their imaginary friend is real — and angry.",
        "Write a scene where two characters argue using only metaphors.",
        "A world where dreams are taxed.",
        "Someone receives postcards from a place that doesn’t exist.",
        "A pandemic that only affects emotions.",
        "A bookstore that appears only at midnight.",
        "Your protagonist learns their story was written by someone else.",
        "A spaceship powered by stories.",
        "A machine that records your final thoughts before death.",
        "A child finds a key that unlocks a voice in their head.",
        "Write a scene involving a secret kept for generations.",
        "A message is found hidden in a famous painting.",
        "Your main character starts forgetting nouns — then names — then themselves.",
        "Describe a conversation between a human and a machine about art.",
        "Write a story that starts with a confession.",
        "A mirror that shows who you could have been.",
        "Two lovers communicate only through graffiti in the city.",
        "A stranger offers to erase one memory — but only one.",
        "A world where written words can be weaponized.",
        "Write about the moment the moon falls from the sky.",
        "A reality show where the prize is rewriting your past.",
        "Your character receives a letter from their future self — warning them.",
        "An archaeologist finds proof of a civilization that never existed.",
        "A new color is discovered, and it drives people mad.",
        "A town where everyone has the same recurring dream — until one night.",
        "Write from the POV of a character lost in a photograph.",
        "Your character discovers a hidden room in their house — with someone in it.",
        "Describe a society where people choose their own names at age 30.",
        "A fortune teller delivers a prophecy that was meant for someone else.",
        "A door appears in your character’s living room. No one else sees it.",
        "Write a comedy set during the apocalypse.",
        "A pen that writes only the truth — no matter what.",
        "Your character is interviewed by a historian from the future.",
        "Describe a party where time moves differently in each room.",
        "A character falls in love with someone from a different timeline.",
        "A world where birthdays determine your fate — literally.",
        "A creature who lives in unfinished stories.",
        "A museum that collects regrets.",
        "Write about someone who steals people’s voices — and sells them.",
        "Your protagonist must teach a class of mythical creatures.",
        "A train that stops only for people with broken hearts.",
        "Your character hears a song no one else can — and it’s getting louder.",
        "A courtroom where characters from different genres are on trial.",
        "Write about a holiday that doesn’t exist — but should.",
        "Describe a character whose lies become reality.",
        "An annual event where people relive one moment of their life.",
        "A library that lets you borrow moments from others’ lives.",
        "Your protagonist must write a story — or vanish.",
        "Write a horror story without using any supernatural elements.",
        "A spaceship crash-lands on Earth — with a familiar face aboard.",
        "A child who remembers their past five lives.",
        "Two people share a soul — and have never met.",
        "A famous author disappears mid-book — and you’re chosen to finish it.",
        "Describe a scene where the world ends quietly.",
        "A machine that prints your destiny, but it’s jammed.",
        "Your character learns they are the villain in someone else’s story.",
        "Write about a secret society of writers who shape reality.",
        "A child writes a story that starts coming true.",
        "A library where books are alive — and arguing.",
        "The stars in the sky begin to rearrange themselves. One message at a time."
    )
    val vocabMap = mapOf(
        "abrogate" to "to revoke or abolish formally",
        "anachronism" to "something out of its proper time",
        "arrant" to "complete and utter",
        "artless" to "without cunning or deceit",
        "asperity" to "harshness of manner or tone",
        "avarice" to "insatiable greed for riches",
        "belligerent" to "hostile and aggressive",
        "bombastic" to "high-sound but with little meaning; inflated",
        "bucolic" to "relating to pleasant countryside or rural life",
        "byzantine" to "excessively complex or intricate",
        "cajole" to "persuade by flattery or coaxing",
        "candour" to "frankness or honesty",
        "castigate" to "to criticize or punish severely",
        "circumlocution" to "the use of many words where fewer would do",
        "conflagration" to "a large and destructive fire",
        "connive" to "to secretly allow or conspire",
        "contumacious" to "stubbornly disobedient",
        "corroborate" to "confirm or give support to",
        "craven" to "very cowardly",
        "debacle" to "a sudden disastrous failure",
        "debauchery" to "excessive indulgence in sensual pleasures",
        "decadent" to "characterized by decay or decline in morals",
        "deleterious" to "harmful or damaging",
        "demagogue" to "a leader who appeals to emotions rather than reason",
        "denouement" to "the outcome of a complex sequence of events",
        "desultory" to "lacking a plan or purpose; random",
        "diaphanous" to "very sheer and light; almost transparent",
        "diffident" to "modest or shy because of lack of self-confidence",
        "disparate" to "fundamentally different or distinct",
        "ebullient" to "overflowing with enthusiasm or excitement",
        "eclectic" to "deriving ideas or style from a broad range of sources",
        "effervescent" to "vivacious and enthusiastic",
        "egregious" to "outstandingly bad or shocking",
        "elucidate" to "make (something) clear; explain",
        "emulate" to "to imitate with the aim of matching or surpassing",
        "enervate" to "to weaken or drain of energy",
        "enigmatic" to "difficult to interpret or understand; mysterious",
        "ephemeral" to "lasting for a very short time",
        "equivocate" to "to speak ambiguously or evasively",
        "erudite" to "having or showing great knowledge",
        "esoteric" to "intended for or likely to be understood by only a few",
        "evanescent" to "soon passing out of sight, memory or existence",
        "exacerbate" to "to make worse or more severe",
        "exculpate" to "to free from blame or guilt",
        "exigent" to "urgent, pressing",
        "explicate" to "to explain in detail",
        "fastidious" to "very attentive to and concerned about accuracy and detail",
        "feckless" to "lacking initiative or strength of character; irresponsible",
        "furtive" to "attempting to avoid notice or attention; secretive",
        "garrulous" to "excessively talkative",
        "grandiloquent" to "using lofty or pompous speech",
        "gregarious" to "fond of company; sociable",
        "harangue" to "a lengthy and aggressive speech",
        "hegemony" to "leadership or dominance by one group over others",
        "iconoclast" to "one who attacks cherished beliefs or institutions",
        "ignominious" to "deserving or causing public disgrace or shame",
        "impecunious" to "having little or no money",
        "imperious" to "assuming power or authority without justification; arrogant",
        "implacable" to "unable to be placated or appeased",
        "inchoate" to "just begun and so not fully formed or developed",
        "incorrigible" to "not able to be corrected or improved",
        "indefatigable" to "persisting tirelessly",
        "indolent" to "lazy or avoiding activity",
        "ineffable" to "too great or extreme to be expressed in words",
        "inexorable" to "impossible to stop or prevent",
        "insidious" to "proceeding in a gradual, subtle way but with harmful effects",
        "intrepid" to "fearless and adventurous",
        "intransigent" to "unwilling to change one’s views or to agree",
        "inveterate" to "having a habit long established; deep-rooted",
        "juxtapose" to "to place side by side for contrast",
        "laconic" to "using very few words; concise",
        "largesse" to "generosity in giving; lavish gift",
        "laudable" to "worthy of praise",
        "lethargic" to "lacking energy; sluggish",
        "lugubrious" to "look­ing or sounding sad and dismal",
        "malaise" to "a general feeling of discomfort or unease",
        "malfeasance" to "wrongful conduct by a public official",
        "maverick" to "an independent thinker or dissenter",
        "meticulous" to "extremely careful and precise",
        "milieu" to "the physical or social setting in which something occurs",
        "misanthrope" to "a person who dislikes humankind",
        "neophyte" to "a beginner or novice",
        "nexus" to "a connection or series of connections",
        "obdurate" to "stubbornly refusing to change",
        "obfuscate" to "to render obscure or unclear",
        "obsequious" to "excessively obedient or attentive",
        "obtuse" to "slow to understand; dull",
        "odious" to "extremely unpleasant; repulsive",
        "onerous" to "involving a great deal of effort and difficulty",
        "opulent" to "rich, luxurious, wealthy",
        "ostensible" to "stated or appearing to be true, but not necessarily so",
        "ostentatious" to "characterized by vulgar or pretentious display",
        "panacea" to "a solution or remedy for all problems",
        "paradigm" to "a typical example or model",
        "paragon" to "a model of excellence",
        "parsimonious" to "unwilling to spend money or use resources",
        "penchant" to "a strong or habitual liking for something",
        "perfidy" to "the state of being deceitful or untrustworthy",
        "perfunctory" to "carried out with minimal effort or reflection",
        "perspicacious" to "having keen understanding or insight",
        "petrichor" to "the smell of earth after rain",
        "plethora" to "a large or excessive amount",
        "platitude" to "a remark that is overused and lacks originality",
        "plebeian" to "common, of the lower class",
        "polemical" to "relating to or involving strongly critical debate",
        "precarious" to "not securely held or in position; dangerously unstable",
        "precocious" to "having abilities earlier than normal",
        "prevaricate" to "to speak or act in an evasive way",
        "proclivity" to "a tendency to choose or do something regularly",
        "prosaic" to "commonplace; lacking poetic beauty",
        "pugnacious" to "eager or quick to argue or fight",
        "punctilious" to "showing great attention to detail or correct behaviour",
        "quixotic" to "exceedingly idealistic; unrealistic",
        "rancorous" to "characterized by bitterness or resentment",
        "recalcitrant" to "having an obstinately uncooperative attitude",
        "recondite" to "little known; abstruse",
        "reprobate" to "an unprincipled person",
        "rescind" to "to revoke, cancel, or repeal",
        "sagacious" to "having keen mental discernment; wise",
        "sanctimonious" to "making a show of being morally superior",
        "sanguine" to "optimistic or positive, especially in bad situation",
        "scintillating" to "brilliantly lively, stimulating",
        "soporific" to "tending to induce drowsiness or sleep",
        "spurious" to "not genuine; false or fake",
        "stipulate" to "to require as an essential condition",
        "strident" to "loud and harsh; grating",
        "stupendous" to "extremely impressive",
        "subjugate" to "to bring under domination or control",
        "sublime" to "of great excellence or beauty",
        "surreptitious" to "kept secret, especially because it would not be approved",
        "sycophant" to "a person who acts obsequiously toward someone important in order to gain advantage",
        "temerity" to "excessive confidence or boldness; audacity",
        "tenacious" to "tending to keep a firm hold; persistent",
        "tranquil" to "free from disturbance; calm",
        "trepidation" to "a feeling of fear or agitation about something that may happen",
        "truculent" to "eager to argue or fight; aggressively defiant",
        "turbulent" to "characterised by conflict, disorder or confusion; violent or unsteady",
        "ubiquitous" to "present, appearing or found everywhere",
        "unctuous" to "excessively flattering or oily in manner",
        "usurp" to "to take a position of power or importance illegally or by force",
        "vainglorious" to "excessively proud of oneself or one’s achievements; overly vain",
        "venerate" to "to regard with great respect",
        "veracity" to "conformity to facts; truthfulness",
        "verbose" to "using more words than necessary; wordy",
        "vicissitude" to "a change of circumstances or fortune, typically one that is unwelcome or unpleasant",
        "vindicate" to "to clear from accusation or suspicion",
        "vitriolic" to "filled with bitter criticism or malice",
        "vociferous" to "voicing or crying out noisily; clamorous",
        "voluble" to "speaking or spoken incessantly and fluently",
        "wane" to "to decrease in size or extent",
        "zealous" to "having or showing great energy or enthusiasm",
        "zenith" to "the highest point; peak"
    )

    val badSentences = mutableListOf(
        "He walked very quickly fast to the store because he needed to get some stuffs that he forgot it.",
        "The dog barked, barked and kept barking loud until the man he was there came back to the place.",
        "She was like, you know, kind of going to maybe do the thing later if she had the time, I guess.",
        "It was a dark night and also stormy too with lots of raining and the lightning was also very loud.",
        "They goes to the beach but it was too sandy and hot so they leaved early and fastly.",
        "John he was a man who liked books that were in the library and he read them a lot many times.",
        "Suddenly out of nowhere the loud noise loudly scared everyone who were already scared before.",
        "The cat sat on the mat and then it sit there again but different this time because it was bored.",
        "I think that maybe possibly he might have been trying to attempt to sort of ask her out maybe.",
        "She runned fastly down the stairs while falling and also she had a phone call at the same exact moment.",
        "The sun was shining so bright it blinded my eyes even though I had sunglasses on my eyes on.",
        "He was the type of person who always used to be the type who talks too much of talking.",
        "They didn't never go to the park no more because of the bees that stung them previously before.",
        "Her eyes was blue like the ocean but not really like that because oceans are green too sometimes.",
        "There is a dog that was outside and it barked and then barked and then barked some more again.",
        "He had did the thing that nobody else didn't ever do before in the past of before.",
        "Walking down the hallway the door suddenly opened which startled me unexpected very much.",
        "The sandwich was tasting like old socks and I know because I maybe probably ate one once.",
        "The room was full of furniture that was furnishing the room full of stuff and chairs and things.",
        "She had a hair that looked like gold and it was long and brown and kind of golden also.",
        "He talks like as if he knows everything even though he doesn’t really know anything actually.",
        "There’s a loud sound that makes a noise and it's sounding loud and noisy in the loud room.",
        "The man, who was old and aged, he looked tired and sleepy and also like he needed a nap.",
        "I seen him yesterday at the mall when he was shopping for shopping things in the shop store.",
        "My phone, it fell down on the ground floor and broke into pieces that was shattered broken.",
        "It was raining rain that was wet and the water fell down like water does from the sky above.",
        "I can’t hardly never find nothing that I want to find when I am looking for it somewhere.",
        "He did a thing that was something that people don't usually do on normal kind of days.",
        "The cake tasted sweetly sugary with sugar sweetness like sugar does when it's sweet tasting.",
        "After they runned the race, they were tired from the running of the racing they did.",
        "The bird flied high up in the sky so high it was like really high above everything else.",
        "She had a voice that sounded like music but more like noise that was musical sounding kinda.",
        "He went inside the room that was inside the house that had a door that opened open.",
        "I don’t want to go to no place where nobody don’t never do nothing fun at all ever.",
        "The stars was shining in the sky above in the nighttime where stars shine bright often.",
        "He looked at her with eyes that were looking like eyes do when they look at someone.",
        "There were lots of people and they all was talking and saying things and speaking words.",
        "Her dress was red like a tomato but also pinkish and kind of orangey depending on light.",
        "The wind blowed hard and fast with blowingness and it made the leaves blow around a lot.",
        "I had went to the restaurant where I eated food that was food they serve at places like that.",
        "They were playing the game of the sport kind and were losing the win because of points.",
        "Time went slow as molasses in January on a cold day when time is slow and cold.",
        "He was standing there, just standing, in a standing way that people stand when they stand.",
        "The computer wasn't turning on so I turned it off again but it was already off though.",
        "She kept saying the same things over and over again repeatedly like a repeating machine.",
        "In the backyard behind the house there was a tree that grew upward into the up sky.",
        "He smiled a smile that showed teeth and happiness and facial expressions of joy and smiling.",
        "The movie was so boring I almost died of boredom from being bored of it during watching.",
        "She had a look that looked like she was looking at something that was looking weirdly."
    )
    val inspiringQuotes = mutableListOf("", "The first draft just needs to be written.", "You've got this.", "Write now, edit later.", "Keep going!", "I believe in you.", "I can't wait to read your book.", "I can see the book's cover already.", "Believe in yourself as much as I believe in you.", "Keep writing!", "Writing isn't a hobby, it's way of life.", "Oof, I feel sorry for your characters in this one.", "Let's get this thing bookstore ready.", "Do I dare say best seller?", "Give your readers all the feels.", "Write, write, write!", "The best books all start with a blank page.", "Your name will look so good in print.", "You can thank me in the acknowledgements ;)", "How pretty will your books cover look when it's done?", "Anyone else feeling in a writing mood?", "Oof, our MC is gonna feel that one in the morning.", "Think our MCs life has been a bit too easy lately...", "Kiss already!", "I love it when a plan comes together.", "I wonder if you'll have a separate author social media account...", "Your name was made to go on a book cover.", "Can't wait to see this in a bookstore!", "You write it, I'll hype you up", "Write the book already!", "Write the words already!", "Watch that sweet sweet word count ticking up.", "You are blowing me away with this scene.", "Oh gosh. Goosebumps. Keep writing.", "Our poor poor MC.", "This might be my favourite scene yet.", "Your writing is on point today.", "Is it me or do we have a soon to be published author in the house?", "Just wait till your friends read your book.", "I assume I'm getting an invite to the book launch.", "So how will we punish our MC today...", "Imagine that feeling when you write the words the end.", "You are on fire today.", "Keep focused pal, we gotta get this thing finished.", "I don't wanna see any more distractions out of you.", "You do the writing and I just sit here. That's the game.", "So do you like always write this slowly or is it just today?", "Finish the chapter!", "Go on. You and I both know you're gonna finish this thing.", "Bring that Pinterest board to life.", "So what will your author signature be like?", "Let's finish this thing.", "The way you write like that? Takes my breath away.", "Gosh, you're talented.", "If you want to mention me in the dedication that would be cool. Just saying.", "You have got to finish this thing. It is so good.", "You might just be my favourite writer.", "One day you're gonna meet all your readers.", "You are so sexy when you write.")
}